### ISSUE TITLE
Support raw `get` that doesn't remove invalid records

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/cache-conf#5]
The use case I have in mind, and that already came up a couple of times (in [Alfy](https://github.com/sindresorhus/alfy)) is the cache-first strategy.

- Do we have data X in the cache?
    - _YES_: Return the cache
    - _NO_: Fetch remotely, store it in the cache for 1 day, and return the data

It might not be present in the cache because 1. it's just not there or 2. the data is outdated. But what to do in case the remote fetch failed due to network issues or the server being down? If we had it in cache, but it's outdated, that outdated will probably be better than nothing.

So suppose the following sample:
```js
const data = cache.get('data');

if (data) {
    return Promise.resolve(data);
}

return got('https://myapi.com/data.json').then(res => {
    cache.set('data', res.body, {maxAge: 86400000});
    return res.body;
});
```

If we find data in the cache return that one, if not fetch it, cache it and return it.

But now I want error handling. If the remote fails and we had data in the cache, I still want that "outdated" data to be returned. This is how it should be done currently.
```js
const cachedData = cache.store['data'] && cache.store['data'].data;

if (!cache.isExpired('data')) {
    return Promise.resolve(cachedData);
}

return got('https://myapi.com/data.json')
    .then(res => {
        cache.set('data', res.body, {maxAge: 86400000});
        return res.body;
    })
    .catch(err => {
        if (cachedData) {
            return cachedData;
        }

        throw err;
    });
```

As you can see, we have to access the `store` property directly.

So I was thinking of adding a new method, or expanding the current `get` method.

1. cache.rawGet(key: string);
2. cache.get(key: string, remove: boolean = true);

```js
const cachedData = cache.get('data', false);

if (!cache.isExpired('data')) {
    return Promise.resolve(cachedData);
}

return got('https://myapi.com/data.json')
    .then(res => {
        cache.set('data', res.body, {maxAge: 86400000});
        return res.body;
    })
    .catch(err => {
        if (cachedData) {
            return cachedData;
        }

        throw err;
    });
```

Any feedback on the API for this?

// @sindresorhus

**Comment by sindresorhus** [comment]
I like `2` the best, but make it an options object and not a boolean trap. Not sure about the name as it's not clear what `{remove: false}` would do. Maybe `{raw: true}`?

**Comment by SamVerschueren** [comment]
Thanks for the feedback! Not sure either about the name. `raw` looks like it returns the raw object as is.

```json
{
    "foo": {
        "timestamp": 1484723090000,
        "data": "bar"
    }
}
```

```js
cache.get('foo');
//=> 'bar'

// Wait long enough untill `foo` expires
cache.get('foo');
//=> undefined; and the store will be empty
```

So when passing `{raw: 'true'}`, it looks like it will return 

```json
{
      "timestamp": 1484723090000,
      "data": "bar"
}
```

Maybe something like `preserve`

```js
cache.get('foo', {preserve: true});
//=> 'bar'

cache.isExpired('foo');
//=> true
```

Not sure either though. Have to think about it for a moment...

**Comment by sindresorhus** [comment]
`preserve` sounds better. Could also go with something explicit like `ignoreMaxAge`.

**Comment by SamVerschueren** [comment]
I'm usually more for explicit, so `ignoreMaxAge` sounds good to me.
